### ISSUE TITLE
Timeout too high?

### ISSUE THREAD

**Issue by EvilOlaf** [gissehel/megacl#2]
Not really a bug, more an enhancement request. 

Actually the timeout is set to 160 seconds which is quite high I think.
30 seconds should be enough. So i don't need to wait that long to see that something's wrong.

Best regards
Olaf

**Comment by gissehel** [comment]
I'll look at that. I don't remember ever using any timeout, I suppose it's either _mega.py_ or rinternal _request_ that set this timeout, I'll look into it.
