### ISSUE TITLE
Xargs support

### ISSUE THREAD

**Issue by EvilOlaf** [gissehel/megacl#3]
Another enhancement request.
Mega supports up to 6 parallel upload and download threads. I wanted to use this feature with xargs.

For example I've got 20 files to upload and want to speed up things by multiple threads.

```
ls | xargs -n 1 -P 6 mcl put
```

won't work because mcl put needs the destination folder as second argument.

I had to solve this the dirty way:

```
ls | sed -r 's/$/\ :8tBCRYbb/g' |xargs -n 2 -P 6  mcl put
```

My suggestion is to add a --directory parameter (or split up in 2 parameters for put and get: --local-directory and --remote-directory) to hand over the target folder first:

```
mcl put --remote-directory=:8tBCRYbb file123
ls | xargs -n 1 -P 6 mcl put --remote-directory=:8tBCRYbb 
```

**Comment by gissehel** [comment]
Ok, I'll do that.
